spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${POSTGRES_DB_NAME:employee_db}
    username: ${POSTGRES_USERNAME:admin}
    password: ${POSTGRES_PASSWORD:password}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate.ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml